kotlin.code.style=official

# Mod Settings
maven_group=de.clickism
archives_base_name=ClickUI

# Mod Properties
mod.id=clickui
mod.version=0.1
mod.minecraft_version=[VERSIONED]
# Comma separated list of target versions
mod.publishing_target_minecraft_versions=[VERSIONED]

# Dependencies
deps.fabric_loader=[VERSIONED]
deps.fabric_api=[VERSIONED]
deps.fabric_kotlin=[VERSIONED]

deps.neoforge=[VERSIONED]
deps.forge=[VERSIONED]
deps.forge_kotlin=[VERSIONED]

# Configuration
org.gradle.configuration-cache=true