modLoader="javafml"
loaderVersion="[1,)"

license="GPL-3.0"
issueTrackerURL="https://github.com/Clickism/ClickUI/issues"
showAsResourcePack=false
clientSideOnly=false

[[mods]]
modId="clickui"
version="${mod_version}"
displayName="ClickUI"
#? if >=26.2 {
iconFile="assets/clickui/icon.png"
#?} else
#logoFile="assets/clickui/icon.png"
authors="Clickism"
description="A modern, declarative, reactive, client-side UI framework for Minecraft."

#[[dependencies.clickui]]
#modId="neoforge"
#type="required"
#versionRange="*"
#side="BOTH"
#
#[[dependencies.clickui]]
#modId = "minecraft"
#type = "required"